const products=[['assets/list-01.png','耐克男子户外运动鞋秋季',1108,'已售47','后跟提拉 便于穿脱'],['assets/list-02.png','耐克女子复古跑鞋风(宽版)',598,'已售100+','橡胶外底 非凡抓地'],['assets/list-03.png','耐克女子透气气垫鞋秋季',1058,'已售1000+','优质鞋面 经久耐穿'],['assets/list-04.png','耐克女子反光装饰气垫鞋',648,'已售88','缓震配置 舒适回弹'],['assets/look-01.png','耐克女子运动休闲鞋秋季',728,'已售5000+','柔软鞋面 日常百搭'],['assets/shoe-head-4.jpeg','耐克女子透气运动鞋秋季',438,'已售400+','轻盈缓震 舒适透气'],['assets/orange-main.png','耐克女子时尚厚底鞋秋季',448,'已售100+','增高设计 稳定支撑'],['assets/shoe-head-5.jpeg','耐克空军一号女子平底运动鞋',799,'已售1万+','经典鞋型 舒适耐穿'],['assets/look-02.png','耐克女子运动短袖夏季新款',578,'已售2000+','柔软面料 自在活动'],['assets/orange-front.png','耐克男子运动鞋轻便透气',608,'已售86','轻便鞋身 日常休闲'],['assets/hero-01.png','Nike耐克官方轻盈缓震跑步鞋',949,'已售100+','泡棉中底 轻盈非凡'],['assets/look-06.png','耐克男子休闲运动上衣',368,'已售100+','宽松版型 舒适有型']].map((p,index)=>({image:p[0],title:p[1],price:p[2],sold:p[3],subtitle:p[4],index}));
const grid=document.querySelector('#productGrid');
const catalogHead=document.querySelector('.catalog-head');
let navTicking=false;
addEventListener('scroll',()=>{if(navTicking)return;navTicking=true;requestAnimationFrame(()=>{catalogHead.classList.toggle('compact',scrollY>48);navTicking=false})},{passive:true});
if(new URLSearchParams(location.search).get('from')==='pdp'){
  const catalog=document.querySelector('.catalog');
  catalog.classList.add('page-enter-left');
  const savedScroll=Number(sessionStorage.getItem('nike-list-scroll')||0);
  requestAnimationFrame(()=>{scrollTo(0,savedScroll);requestAnimationFrame(()=>catalog.classList.remove('page-enter-left'))});
}
function render(items){grid.innerHTML=items.map((p,index)=>`<article class="product-card" tabindex="0" role="link"><div class="photo"><img src="${p.image}" alt="${p.title}"></div><div class="product-copy"><h2 class="product-title">${p.title}</h2><p class="subline">${p.subtitle}</p><div class="price-row">¥<strong>${p.price}</strong><small>补贴后</small><span class="sold">${p.sold}</span></div><div class="meta-shot"><img src="assets/list-meta-${index%2?'right':'left'}.png" alt="限时红包、小黑盒新品和购物车" /></div></div></article>`).join('')}
render(products);
grid.addEventListener('click',event=>{if(event.target.closest('.product-card')){sessionStorage.setItem('nike-list-scroll',String(scrollY));document.querySelector('.catalog').classList.add('page-leave-left');setTimeout(()=>{location.href='index.html?from=list'},270)}});
grid.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.closest('.product-card'))location.href='index.html'});
document.querySelectorAll('[data-sort]').forEach(button=>button.addEventListener('click',()=>{const next=[...products],type=button.dataset.sort;if(type==='price')next.sort((a,b)=>a.price-b.price);if(type==='sales')next.sort((a,b)=>b.index-a.index);if(type==='new')next.reverse();render(next);scrollTo({top:0,behavior:'smooth'})}));
let remaining=1351;setInterval(()=>{remaining=Math.max(0,remaining-1);document.querySelector('#countdown').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`},1000);
const gate=document.querySelector('#passwordGate'),form=document.querySelector('#passwordForm'),input=document.querySelector('#passwordInput'),error=document.querySelector('#passwordError');if(sessionStorage.getItem('nike-demo-access')==='granted')gate.classList.add('hidden');async function digest(value){const data=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return[...new Uint8Array(data)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}form.addEventListener('submit',async event=>{event.preventDefault();if(await digest(input.value)==='d521104a1c7a8a278a7212edf63856ca447bf3c2b4296c80c7c49afa13ed4cc1'){sessionStorage.setItem('nike-demo-access','granted');gate.classList.add('hidden');return}error.textContent='密码不正确，请重新输入';input.select()});if('serviceWorker'in navigator&&location.protocol.startsWith('http'))addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
