const products=[['assets/shoe-head-1.png','耐克男子户外运动鞋秋季新款公路跑鞋',1399,'已售200+'],['assets/shoe-head-2.png','耐克女子复古跑鞋风限定款休闲运动鞋',598,'已售100+'],['assets/look-08.png','耐克女子运动休闲鞋秋季透气缓震',1058,'已售1000+'],['assets/shoe-head-3.jpeg','耐克女子反光装饰气垫鞋秋季新款',648,'已售88'],['assets/look-01.png','耐克男子速干运动上衣日常休闲短袖',728,'已售5000+'],['assets/shoe-head-4.jpeg','耐克女子透气运动鞋舒适轻盈',438,'已售400+'],['assets/orange-main.png','耐克男子户外跑步鞋缓震耐磨新款',1108,'已售47'],['assets/shoe-head-5.jpeg','耐克空军一号女子平底运动鞋',799,'已售1万+'],['assets/look-02.png','耐克女子运动短袖夏季新款',578,'已售2000+'],['assets/orange-front.png','耐克男子运动鞋轻便透气休闲鞋',608,'已售86'],['assets/hero-01.png','Nike耐克官方轻盈缓震跑步鞋',949,'已售100+'],['assets/look-06.png','耐克男子休闲运动上衣宽松版型',368,'已售100+']].map((p,index)=>({image:p[0],title:p[1],price:p[2],sold:p[3],index}));
const grid=document.querySelector('#productGrid');
function render(items){grid.innerHTML=items.map(p=>`<article class="product-card" tabindex="0" role="link"><div class="photo"><img src="${p.image}" alt="${p.title}"><img class="nike" src="assets/swoosh.svg" alt=""></div><div class="product-copy"><h2 class="product-title">${p.title}</h2><p class="subline">轻盈缓震｜舒适透气</p><div class="price-row">¥<strong>${p.price}</strong><small>补贴后</small><span class="sold">${p.sold}</span></div><div class="meta"><span class="promo">限时红包</span><span class="shop">● 小黑盒新品</span><button class="add-cart" aria-label="加入购物车">♧</button></div></div></article>`).join('')}
render(products);
grid.addEventListener('click',event=>{if(event.target.closest('.add-cart')){event.preventDefault();return}if(event.target.closest('.product-card'))location.href='index.html'});grid.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.closest('.product-card'))location.href='index.html'});
document.querySelectorAll('[data-sort]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-sort]').forEach(item=>item.classList.toggle('active',item===button));const next=[...products],type=button.dataset.sort;if(type==='price')next.sort((a,b)=>a.price-b.price);if(type==='sales')next.sort((a,b)=>b.index-a.index);if(type==='new')next.reverse();render(next);scrollTo({top:0,behavior:'smooth'})}));
let remaining=1351;setInterval(()=>{remaining=Math.max(0,remaining-1);document.querySelector('#countdown').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`},1000);
const gate=document.querySelector('#passwordGate'),form=document.querySelector('#passwordForm'),input=document.querySelector('#passwordInput'),error=document.querySelector('#passwordError');if(sessionStorage.getItem('nike-demo-access')==='granted')gate.classList.add('hidden');async function digest(value){const data=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return[...new Uint8Array(data)].map(byte=>byte.toString(16).padStart(2,'0')).join('')}form.addEventListener('submit',async event=>{event.preventDefault();if(await digest(input.value)==='d521104a1c7a8a278a7212edf63856ca447bf3c2b4296c80c7c49afa13ed4cc1'){sessionStorage.setItem('nike-demo-access','granted');gate.classList.add('hidden');return}error.textContent='密码不正确，请重新输入';input.select()});
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
